import type { Exercise } from '../types';

export const POPULAR_EXERCISES: Omit<Exercise, '_id' | '_creationTime' | 'userId'>[] = [
  {
    name: 'Kniebeuge (Squat)',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Bankdrücken',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Kreuzheben',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Überkopfdrücken',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Klimmzüge',
    trackWeight: false,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Liegestütze',
    trackWeight: false,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Langhantelrudern',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Dips',
    trackWeight: false,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Bizeps-Curls',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Planks',
    trackWeight: false,
    trackReps: false,
    trackTime: true,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: false,
      time: true,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Laufen',
    trackWeight: false,
    trackReps: false,
    trackTime: true,
    trackDistance: true,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: false,
      time: true,
      distance: true,
      notes: true,
    },
  },
  {
    name: 'Radfahren',
    trackWeight: false,
    trackReps: false,
    trackTime: true,
    trackDistance: true,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: false,
      time: true,
      distance: true,
      notes: true,
    },
  },
  {
    name: 'Burpees',
    trackWeight: false,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Mountain Climbers',
    trackWeight: false,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: false,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
  {
    name: 'Lunges',
    trackWeight: true,
    trackReps: true,
    trackTime: false,
    trackDistance: false,
    trackNotes: true,
    isPopular: true,
    trackingComponents: {
      weight: true,
      reps: true,
      time: false,
      distance: false,
      notes: true,
    },
  },
];
